spring:
  application:
    name: exercise_5
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5433/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      show_sql: true
    connection:
      driver_class: org.postgresql.Driver

    open-in-view: false
    properties:
      hibernate:

  liquibase:
    enabled: false